name: "Bug Report: Browser Extension"
description: Report a bug in the browser extension
labels: ["bug", "extension", "needs approval"]
body:
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - Brave
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: Which version of the browser are you running?
      placeholder: "e.g., Chrome 120"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Which version of the extension are you running?
      placeholder: "e.g., 1.7.6"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: "e.g., macOS 15.2, Windows 11, Ubuntu 24.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Console Errors
      description: Add screenshots, screen recordings, or browser console errors if applicable.
      placeholder: Attach evidence here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful.
      placeholder: Add any additional context here...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ##### House rules
        - If this issue has a `needs approval` label, don't start coding yet. Wait until a core member approves the request by removing this label.
        - Your ideas are invaluable! However, they undergo review to ensure alignment with the product's direction.
        - Follow best practices in our [Contributor Docs](https://github.com/calcom/companion/blob/main/CONTRIBUTING.md)
