name: "Bug Report: iOS"
description: Report a bug in the iOS app
labels: ["bug", "ios", "needs approval"]
body:
  - type: input
    id: ios-version
    attributes:
      label: iOS Version
      description: Which version of iOS are you running?
      placeholder: "e.g., 17.2"
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: Device Model
      description: Which device are you using?
      placeholder: "e.g., iPhone 15 Pro"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Which version of the companion app are you running?
      placeholder: "e.g., 1.0.4"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Tap on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: Add screenshots or screen recordings if applicable.
      placeholder: Attach evidence here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful (e.g., crash logs, console output).
      placeholder: Add any additional context here...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ##### House rules
        - If this issue has a `needs approval` label, don't start coding yet. Wait until a core member approves the request by removing this label.
        - Your ideas are invaluable! However, they undergo review to ensure alignment with the product's direction.
        - Follow best practices in our [Contributor Docs](https://github.com/calcom/companion/blob/main/CONTRIBUTING.md)
